[programs.devnet]
solana_jobs = "EkfFT2G6Vs9diETs31dhtS89kdZEQZdCUsXh7c1MsZyz"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/stephenjohnson/.config/solana/id.json"

[scripts]
test = "node tests/solana-jobs.js"

[test]
startup_wait = 10000